// Log collection (#216). Grafana Alloy as a DaemonSet, shipping every pod's
// stdout/stderr to Loki.
//
// Alloy, not promtail: promtail reached end-of-life (LTS ended Feb 2026, no
// further releases) and Alloy is its stated successor with the same pipeline
// components. Starting a new install on promtail would be starting on a
// migration.
//
// COLLECTION METHOD — read this before changing anything below. Two ways exist
// to get container logs:
//   1. `loki.source.file` tailing the node's `/var/log/pods/**` symlinks. Needs
//      a hostPath mount of `/var/log` and, in practice, elevated privileges to
//      traverse it.
//   2. `loki.source.kubernetes`, which streams from the Kubernetes **pod log
//      API** (the same endpoint `kubectl logs -f` uses). Needs no host mounts
//      and no privileges at all — just RBAC on `pods/log`.
// We use (2). It is the minimal-privilege option, and it is also the one that
// does not care that Talos uses containerd with its own log layout rather than
// the `/var/lib/docker/containers` path most examples assume. There are
// therefore NO hostPath volumes in this DaemonSet, deliberately.

import { createHash } from "node:crypto";
import * as k8s from "@pulumi/kubernetes";
import { ALLOY_IMAGE, LOKI_PORT, OBSERVABILITY_NAMESPACE } from "./constants.ts";
import type { LokiResources } from "./loki.ts";

const ALLOY_NAME = "alloy";
const CONFIG_MAP_NAME = "alloy-config";
const SERVICE_ACCOUNT_NAME = "alloy";
const CLUSTER_ROLE_NAME = "alloy";
const CLUSTER_ROLE_BINDING_NAME = "alloy";
const CONFIG_MOUNT_PATH = "/etc/alloy";
const CONFIG_FILE_NAME = "config.alloy";

/** Alloy's own HTTP server: the debug UI on `/` and its Prometheus metrics on `/metrics`. */
const ALLOY_HTTP_PORT = 12345;

/** In-cluster DNS of the Loki service installed by `loki.ts`. */
const LOKI_PUSH_URL = `http://loki.${OBSERVABILITY_NAMESPACE}.svc.cluster.local:${LOKI_PORT}/loki/api/v1/push`;

/**
 * The Alloy pipeline, in Alloy's own configuration syntax (River — HCL-shaped
 * blocks and expressions). It is NOT YAML; indentation is cosmetic and `=` is
 * required. Written as a string because there is no typed builder for it.
 *
 * Shape: discovery.kubernetes → discovery.relabel → loki.source.kubernetes →
 * loki.process → loki.write.
 *
 * ── LABEL CARDINALITY — the one rule that matters ──────────────────────────
 * Every distinct combination of label VALUES is a separate stream in Loki,
 * with its own index entry and its own set of chunks. The label set below is
 * `namespace`, `pod`, `container`, `app`, `service`, `level` and nothing else,
 * and that is a deliberate ceiling.
 *
 * NEVER promote a request id, trace id, user id, span id, session id, URL
 * path, error message, or any other unbounded field to a label. Doing so
 * creates one stream per request: the index explodes, the ingester holds
 * thousands of tiny open chunks, and queries that used to take a second start
 * timing out. This is the single most common way a working Loki install is
 * destroyed, and it is not recoverable without deleting data.
 *
 * Those fields are still queryable — they stay in the JSON log line, which
 * `| json` filters at query time, or they can be attached as structured
 * metadata (`stage.structured_metadata`), which is indexed per-chunk rather
 * than per-stream. Filter, do not label.
 */
function buildAlloyConfig(): string {
  return `// GENERATED by infra/src/observability/alloy.ts — edit that file, not this.

// Every pod in the cluster, from the Kubernetes API.
discovery.kubernetes "pods" {
  role = "pod"
}

discovery.relabel "pods" {
  targets = discovery.kubernetes.pods.targets

  // This is a DaemonSet: without this keep rule EVERY replica would tail EVERY
  // pod in the cluster, multiplying both log volume and API-server load by the
  // node count. NODE_NAME comes from the pod's own spec.nodeName (see below).
  rule {
    source_labels = ["__meta_kubernetes_pod_node_name"]
    regex         = sys.env("NODE_NAME")
    action        = "keep"
  }

  // The low-cardinality label set. See the cardinality note above before
  // adding anything here.
  rule {
    source_labels = ["__meta_kubernetes_namespace"]
    target_label  = "namespace"
  }
  rule {
    source_labels = ["__meta_kubernetes_pod_name"]
    target_label  = "pod"
  }
  rule {
    source_labels = ["__meta_kubernetes_pod_container_name"]
    target_label  = "container"
  }
  // Best-effort workload identity for pods that carry either convention.
  rule {
    source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name", "__meta_kubernetes_pod_label_app"]
    separator     = ";"
    regex         = "([^;]+);.*|;(.+)"
    replacement   = "\${1}\${2}"
    target_label  = "app"
  }
}

// Streams container logs from the Kubernetes pod log API. No host mounts, no
// privileges — see the COLLECTION METHOD note in alloy.ts.
loki.source.kubernetes "pods" {
  targets    = discovery.relabel.pods.output
  forward_to = [loki.process.pino.receiver]
}

loki.process "pino" {
  forward_to = [loki.write.default.receiver]

  // Our backend services (api, guest-api, worker) log
  // pino JSON on stdout. pino's own field names: numeric \`level\`, message
  // \`msg\`, epoch-millis \`time\`, plus \`service\` and \`env\` bound as base
  // fields by packages/logger. Non-JSON lines from third-party images simply
  // extract nothing and fall through unlabelled.
  stage.json {
    expressions = {
      level   = "level",
      msg     = "msg",
      service = "service",
      env     = "env",
      time    = "time",
    }
  }

  // pino writes \`level\` as a NUMBER (30 = info, 50 = error). Left alone the
  // label would read {level="30"}, which nothing in Grafana understands.
  stage.template {
    source   = "level"
    template = "{{ if eq .Value \\"10\\" }}trace{{ else if eq .Value \\"20\\" }}debug{{ else if eq .Value \\"30\\" }}info{{ else if eq .Value \\"40\\" }}warn{{ else if eq .Value \\"50\\" }}error{{ else if eq .Value \\"60\\" }}fatal{{ else }}{{ .Value }}{{ end }}"
  }

  // Use the application's own timestamp so a backlogged collector does not
  // stamp an hour-old line with the time it happened to be read.
  stage.timestamp {
    source = "time"
    format = "UnixMs"
  }

  // ONLY these two are promoted, on top of the k8s labels set above. Both are
  // bounded: \`service\` by the number of services we deploy, \`level\` by the
  // six pino levels. Adding a third promotion here needs the cardinality
  // argument in alloy.ts answered first.
  stage.labels {
    values = {
      service = "service",
      level   = "level",
    }
  }
}

loki.write "default" {
  endpoint {
    url = "${LOKI_PUSH_URL}"
  }
}
`;
}

export type AlloyArgs = {
  provider: k8s.Provider;
  namespace: k8s.core.v1.Namespace;
  /**
   * Optional ordering hint only. Alloy does not NEED Loki to exist — `loki.write`
   * buffers and retries — but creating the collector before its sink just means
   * a few minutes of push errors in the logs on a fresh install.
   */
  loki?: LokiResources;
};

export type AlloyResources = {
  serviceAccount: k8s.core.v1.ServiceAccount;
  clusterRole: k8s.rbac.v1.ClusterRole;
  clusterRoleBinding: k8s.rbac.v1.ClusterRoleBinding;
  config: k8s.core.v1.ConfigMap;
  daemonSet: k8s.apps.v1.DaemonSet;
  /** Named `alloy` — Prometheus scrapes Alloy's own `/metrics` through it. */
  service: k8s.core.v1.Service;
};

/**
 * @public — installs the Alloy log-collection DaemonSet. Depends on nothing
 * but the Namespace: it will buffer and retry if Loki is not up yet.
 */
export function installAlloy(args: AlloyArgs): AlloyResources {
  const { provider, namespace, loki } = args;
  const alloyConfig = buildAlloyConfig();
  const options = { provider, dependsOn: [namespace] };
  const labels = { "app.kubernetes.io/name": ALLOY_NAME };

  const serviceAccount = new k8s.core.v1.ServiceAccount(
    SERVICE_ACCOUNT_NAME,
    {
      metadata: { name: SERVICE_ACCOUNT_NAME, namespace: OBSERVABILITY_NAMESPACE, labels },
    },
    options,
  );

  const clusterRole = new k8s.rbac.v1.ClusterRole(
    CLUSTER_ROLE_NAME,
    {
      metadata: { name: CLUSTER_ROLE_NAME, labels },
      rules: [
        {
          apiGroups: [""],
          // `pods/log` is the one that actually matters: it is the endpoint
          // loki.source.kubernetes reads from, and it is what buys us the
          // no-hostPath, no-privileges deployment. The rest are what
          // discovery.kubernetes needs to enumerate and relabel targets.
          resources: [
            "pods",
            "pods/log",
            "nodes",
            "nodes/proxy",
            "namespaces",
            "services",
            "endpoints",
          ],
          verbs: ["get", "list", "watch"],
        },
      ],
    },
    { provider },
  );

  const clusterRoleBinding = new k8s.rbac.v1.ClusterRoleBinding(
    CLUSTER_ROLE_BINDING_NAME,
    {
      metadata: { name: CLUSTER_ROLE_BINDING_NAME, labels },
      roleRef: {
        apiGroup: "rbac.authorization.k8s.io",
        kind: "ClusterRole",
        name: CLUSTER_ROLE_NAME,
      },
      subjects: [
        {
          kind: "ServiceAccount",
          name: SERVICE_ACCOUNT_NAME,
          namespace: OBSERVABILITY_NAMESPACE,
        },
      ],
    },
    { provider, dependsOn: [namespace, serviceAccount, clusterRole] },
  );

  const config = new k8s.core.v1.ConfigMap(
    CONFIG_MAP_NAME,
    {
      metadata: { name: CONFIG_MAP_NAME, namespace: OBSERVABILITY_NAMESPACE, labels },
      data: { [CONFIG_FILE_NAME]: alloyConfig },
    },
    options,
  );

  const daemonSet = new k8s.apps.v1.DaemonSet(
    ALLOY_NAME,
    {
      metadata: { name: ALLOY_NAME, namespace: OBSERVABILITY_NAMESPACE, labels },
      spec: {
        selector: { matchLabels: labels },
        template: {
          metadata: {
            labels,
            // Roll the pod when its config changes: a mounted ConfigMap updates
            // in place, but the process only reads it at boot, so without this
            // a config change sits deployed-but-inert until an unrelated
            // restart.
            annotations: {
              "checksum/config": createHash("sha256").update(alloyConfig).digest("hex"),
            },
          },
          spec: {
            serviceAccountName: SERVICE_ACCOUNT_NAME,
            // The one node today is untainted, but a DaemonSet that silently
            // skips control-plane nodes is a gap that only shows up the day a
            // second node is added — and then the missing logs are the logs
            // you need.
            tolerations: [
              {
                key: "node-role.kubernetes.io/control-plane",
                operator: "Exists",
                effect: "NoSchedule",
              },
            ],
            containers: [
              {
                name: ALLOY_NAME,
                image: ALLOY_IMAGE,
                args: [
                  "run",
                  `${CONFIG_MOUNT_PATH}/${CONFIG_FILE_NAME}`,
                  // Component state (WAL, target progress). An emptyDir is
                  // enough: the API-based source tracks its read position in
                  // memory anyway, so there is no on-disk cursor worth keeping.
                  "--storage.path=/tmp/alloy",
                  // Must bind 0.0.0.0, not the default localhost, or the
                  // metrics endpoint is unreachable from Prometheus.
                  `--server.http.listen-addr=0.0.0.0:${ALLOY_HTTP_PORT}`,
                ],
                env: [
                  // Feeds the `keep` relabel rule that limits each DaemonSet
                  // pod to its own node's containers.
                  {
                    name: "NODE_NAME",
                    valueFrom: { fieldRef: { fieldPath: "spec.nodeName" } },
                  },
                ],
                ports: [{ name: "http", containerPort: ALLOY_HTTP_PORT }],
                securityContext: {
                  // Reading logs over the API needs no host access at all, so
                  // the container keeps nothing.
                  privileged: false,
                  allowPrivilegeEscalation: false,
                  capabilities: { drop: ["ALL"] },
                },
                readinessProbe: {
                  httpGet: { path: "/-/ready", port: "http" },
                  initialDelaySeconds: 10,
                  periodSeconds: 10,
                },
                // No cpu limit: throttling the collector during a log burst is
                // exactly when it must not fall behind.
                resources: {
                  requests: { cpu: "50m", memory: "128Mi" },
                  limits: { memory: "512Mi" },
                },
                volumeMounts: [
                  { name: "config", mountPath: CONFIG_MOUNT_PATH },
                  { name: "storage", mountPath: "/tmp/alloy" },
                ],
              },
            ],
            volumes: [
              { name: "config", configMap: { name: CONFIG_MAP_NAME } },
              { name: "storage", emptyDir: {} },
            ],
          },
        },
      },
    },
    {
      ...options,
      dependsOn: [
        namespace,
        config,
        clusterRoleBinding,
        ...(loki === undefined ? [] : [loki.deployment, loki.service]),
      ],
    },
  );

  const service = new k8s.core.v1.Service(
    ALLOY_NAME,
    {
      metadata: { name: ALLOY_NAME, namespace: OBSERVABILITY_NAMESPACE, labels },
      spec: {
        type: "ClusterIP",
        selector: labels,
        ports: [{ name: "http", port: ALLOY_HTTP_PORT, targetPort: "http" }],
      },
    },
    options,
  );

  return { serviceAccount, clusterRole, clusterRoleBinding, config, daemonSet, service };
}
