// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run `bun run apps:gen` after changing a feature facet; commit the result.

export * from "../../apps/api/src/db/schema";
export * from "../booth/schema";
export * from "../ctrl/schema";
export * from "../deploys/schema";
export * from "../events/schema";
export * from "../felogs/schema";
export * from "../goals/schema";
export * from "../guest-wifi/schema";
export * from "../hooks/schema";
export * from "../injections/schema";
export * from "../notif/schema";
export * from "../panel-update/schema";
export * from "../scenes/schema";
export * from "../wakes/schema";
export * from "../weather/schema";
export * from "../weight/schema";
