// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/worker.ts.
// Re-run `bun run apps:gen` after changing an App worker facet; commit the result.

import type { Worker } from "@app-kit";
import { cycles as acCycles } from "../ac/worker";
import { cycles as ctrlCycles } from "../ctrl/worker";
import { cycles as soundCycles } from "../sound/worker";
import { cycles as weatherCycles } from "../weather/worker";

export const GENERATED_WORKERS: readonly Worker[] = [
  ...acCycles,
  ...ctrlCycles,
  ...soundCycles,
  ...weatherCycles,
];
