// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run `bun run apps:gen` after changing a feature facet; commit the result.

import { purgeCron as deploys_purgeCron } from "../deploys/jobs";
import { purgeCron as felogs_purgeCron } from "../felogs/jobs";
import { purgeCron as guestWifi_purgeCron } from "../guest-wifi/jobs";
import { purgeCron as wakes_purgeCron } from "../wakes/jobs";
import { purgeCron as weather_purgeCron } from "../weather/jobs";

export const CRON_HANDLERS: Record<string, () => Promise<void>> = {
  "deploys-purge": deploys_purgeCron.run,
  "felogs-purge": felogs_purgeCron.run,
  "guest-wifi-purge": guestWifi_purgeCron.run,
  "wake-photo-purge": wakes_purgeCron.run,
  "weather-purge": weather_purgeCron.run,
};
