// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run `bun run apps:gen` after changing a feature facet; commit the result.

export interface GeneratedCron {
  name: string;
  schedule: string;
  source: string;
}

export const GENERATED_CRONS: readonly GeneratedCron[] = [
  { name: "deploys-purge", schedule: "0 5 * * *", source: "feature:deploys" },
  { name: "felogs-purge", schedule: "0 4 * * *", source: "feature:felogs" },
  { name: "guest-wifi-purge", schedule: "0 2 * * *", source: "feature:guest-wifi" },
  { name: "wake-photo-purge", schedule: "0 4 * * *", source: "feature:wakes" },
  { name: "weather-purge", schedule: "0 3 * * *", source: "feature:weather" },
];
