// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run `bun run apps:gen` after changing a feature facet; commit the result.

import type { HttpRoute } from "@app-kit";
import { routes as wakesHttp } from "../wakes/http";
import { routes as boothHttp } from "../../apps/api/src/http/booth.http";

export const GENERATED_ROUTES: readonly HttpRoute[] = [
  ...wakesHttp,
  ...boothHttp,
];
