// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run `bun run apps:gen` after changing a feature facet; commit the result.

import type { JobSpec } from "@www/core";
import { jobs as notifJobs } from "../notif/jobs";

export const GENERATED_JOBS: readonly JobSpec[] = [
  ...notifJobs,
];
