// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run `bun run apps:gen` after changing a feature facet; commit the result.

import { mergeRouters } from "@app-kit/server";
import { api as acApi } from "../ac/api";
import { api as boothApi } from "../booth/api";
import { api as ctrlApi } from "../ctrl/api";
import { api as soundApi } from "../sound/api";
import { api as wakesApi } from "../wakes/api";
import { api as weatherApi } from "../weather/api";

export const featureAppRouter = mergeRouters(acApi, boothApi, ctrlApi, soundApi, wakesApi, weatherApi);
