// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run `bun run apps:gen` after changing a feature facet; commit the result.

import { mergeRouters } from "@app-kit/server";
import { api as acApi } from "../ac/api";
import { api as deploysApi } from "../deploys/api";
import { api as dogcamApi } from "../dogcam/api";
import { api as eventsApi } from "../events/api";
import { api as guestWifiApi } from "../guest-wifi/api";
import { api as networkApi } from "../network/api";
import { api as notifApi } from "../notif/api";
import { api as teslaApi } from "../tesla/api";
import { api as weatherApi } from "../weather/api";
import { api as weightApi } from "../weight/api";

export const featureAppRouter = mergeRouters(acApi, deploysApi, dogcamApi, eventsApi, guestWifiApi, networkApi, notifApi, teslaApi, weatherApi, weightApi);
