// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/manifest.ts.
// Re-run `bun run apps:gen` after changing a Tile; commit the result.

export interface GeneratedTile {
  id: string;
  appId: string;
  label: string;
  worldCol: number;
  worldRow: number;
  cols: number;
  rows: number;
  home: boolean;
  sensitive: boolean;
  private: boolean;
  source: "feature" | "registry";
}

export const GENERATED_TILES: readonly GeneratedTile[] = [
  {
    id: "tile_ac",
    appId: "tile_ac",
    label: "Climate · A/C",
    worldCol: 30,
    worldRow: 30,
    cols: 4,
    rows: 3,
    home: false,
    sensitive: false,
    private: false,
    source: "feature",
  },
  {
    id: "tile_booth",
    appId: "tile_booth",
    label: "Photo Booth",
    worldCol: 27,
    worldRow: 24,
    cols: 2,
    rows: 2,
    home: false,
    sensitive: false,
    private: true,
    source: "feature",
  },
  {
    id: "tile_clock",
    appId: "tile_events",
    label: "Clock",
    worldCol: 29,
    worldRow: 27,
    cols: 5,
    rows: 3,
    home: false,
    sensitive: false,
    private: false,
    source: "feature",
  },
  {
    id: "tile_ctrl",
    appId: "tile_ctrl",
    label: "Controls",
    worldCol: 22,
    worldRow: 24,
    cols: 5,
    rows: 6,
    home: true,
    sensitive: false,
    private: false,
    source: "feature",
  },
  {
    id: "tile_hourly",
    appId: "tile_weather",
    label: "Next 12 Hours",
    worldCol: 22,
    worldRow: 30,
    cols: 4,
    rows: 3,
    home: false,
    sensitive: false,
    private: false,
    source: "feature",
  },
  {
    id: "tile_sound",
    appId: "tile_sound",
    label: "Sound System",
    worldCol: 29,
    worldRow: 24,
    cols: 5,
    rows: 3,
    home: false,
    sensitive: false,
    private: false,
    source: "feature",
  },
  {
    id: "tile_wakes",
    appId: "tile_wakes",
    label: "Activity",
    worldCol: 27,
    worldRow: 26,
    cols: 2,
    rows: 2,
    home: false,
    sensitive: true,
    private: false,
    source: "feature",
  },
  {
    id: "tile_weath",
    appId: "tile_weather",
    label: "Weather Now",
    worldCol: 26,
    worldRow: 30,
    cols: 4,
    rows: 3,
    home: false,
    sensitive: false,
    private: false,
    source: "feature",
  },
  {
    id: "tile_wifi",
    appId: "tile_wifi",
    label: "Wi-Fi",
    worldCol: 27,
    worldRow: 28,
    cols: 2,
    rows: 2,
    home: false,
    sensitive: false,
    private: false,
    source: "feature",
  },
];
