// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: apps/web/src/lib/tile-registry.ts (+ features/*/manifest.ts in
// Slice 5). Re-run `bun run apps:gen` after changing a tile; commit the result.

export interface GeneratedTile {
  label: string;
  worldCol: number;
  worldRow: number;
  cols: number;
  rows: number;
}
export interface GeneratedApp {
  id: string;
  tile: GeneratedTile;
  guestExposed: boolean;
  home: boolean;
  sensitive: boolean;
  source: "feature" | "registry";
}

export const GENERATED_TILES: readonly GeneratedApp[] = [
  {
    id: "tile_ac",
    tile: { label: "Climate · A/C", worldCol: 30, worldRow: 24, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_booth",
    tile: { label: "Photo Booth", worldCol: 30, worldRow: 22, cols: 2, rows: 2 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_clock",
    tile: { label: "Clock", worldCol: 26, worldRow: 27, cols: 5, rows: 3 },
    guestExposed: false,
    home: true,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_ctrl",
    tile: { label: "Controls", worldCol: 31, worldRow: 27, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_deploys",
    tile: { label: "Deploys", worldCol: 34, worldRow: 24, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_dogcam",
    tile: { label: "Living Room Cam", worldCol: 38, worldRow: 27, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_event",
    tile: { label: "Upcoming", worldCol: 30, worldRow: 30, cols: 4, rows: 2 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_felogs",
    tile: { label: "Frontend Logs", worldCol: 26, worldRow: 30, cols: 4, rows: 2 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_guestwifi",
    tile: { label: "Guest", worldCol: 28, worldRow: 22, cols: 2, rows: 2 },
    guestExposed: true,
    home: false,
    sensitive: false,
    source: "feature",
  },
  {
    id: "tile_hourly",
    tile: { label: "Next 12 Hours", worldCol: 22, worldRow: 24, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_notif",
    tile: { label: "Notifications", worldCol: 38, worldRow: 24, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_quickplay",
    tile: { label: "Quick Play", worldCol: 26, worldRow: 32, cols: 4, rows: 2 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_sound",
    tile: { label: "Sound System", worldCol: 22, worldRow: 31, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_tesla",
    tile: { label: "Tesla", worldCol: 22, worldRow: 27, cols: 4, rows: 4 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_tv",
    tile: { label: "TV", worldCol: 18, worldRow: 24, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_tvapps",
    tile: { label: "TV Apps", worldCol: 30, worldRow: 32, cols: 4, rows: 2 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_wakes",
    tile: { label: "Activity", worldCol: 34, worldRow: 30, cols: 2, rows: 2 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_weath",
    tile: { label: "Weather Now", worldCol: 26, worldRow: 24, cols: 4, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_weight",
    tile: { label: "Weight", worldCol: 34, worldRow: 22, cols: 3, rows: 2 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "registry",
  },
  {
    id: "tile_wifi",
    tile: { label: "Network", worldCol: 35, worldRow: 27, cols: 3, rows: 3 },
    guestExposed: false,
    home: false,
    sensitive: false,
    source: "feature",
  },
];
