// AUTO-GENERATED by `bun run apps:gen` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,detail}.ts.
// Re-run `bun run apps:gen` after changing an App web facet; commit the result.

import { createWebRegistry } from "@app-kit";
import acManifest from "../ac/manifest";
import boothManifest from "../booth/manifest";
import ctrlManifest from "../ctrl/manifest";
import eventsManifest from "../events/manifest";
import expoManifest from "../expo/manifest";
import soundManifest from "../sound/manifest";
import wakesManifest from "../wakes/manifest";
import weatherManifest from "../weather/manifest";
import wifiManifest from "../wifi/manifest";
import { tileViews as boothTileViews } from "../booth/detail";
import { tileViews as ctrlTileViews } from "../ctrl/detail";
import { tileViews as soundTileViews } from "../sound/detail";
import { tileViews as wakesTileViews } from "../wakes/detail";

const manifests = [
  acManifest,
  boothManifest,
  ctrlManifest,
  eventsManifest,
  expoManifest,
  soundManifest,
  wakesManifest,
  weatherManifest,
  wifiManifest,
];

const tileViews = [
  ...boothTileViews,
  ...ctrlTileViews,
  ...soundTileViews,
  ...wakesTileViews,
];

export const {
  TILE_REGISTRY,
  HOME_TILE,
  registryEntryForComponent,
  registryEntryForTileId,
  accessFor,
  getTileDetailEntry,
} = createWebRegistry(manifests, tileViews);

export type { TileAccessPolicy, TileRegistryEntry } from "@app-kit";
