import type { AppModel, CollectedApp, CollectedFeature } from "./collect";

/**
 * The codegen emitter (Task 3.3). Renders the collected {@link AppModel} into a
 * deterministic TypeScript module string. This slice is a byte-identical no-op:
 * the emitted `features/_generated/tiles.gen.ts` is a typed projection of the
 * SAME data the runtime already reads from `TILE_REGISTRY`, produced purely so
 * the codegen consistency check (validate → emit → format) has a committed
 * artifact to diff against. The runtime keeps consuming the registry directly
 * this slice; nothing imports the generated module yet (Slice 5 flips consumers
 * once the model unions in the features manifests).
 *
 * Determinism is the whole point: apps are sorted by `id` before rendering and
 * every field is emitted in a fixed key order, so `renderTiles(model)` is stable
 * across runs and `bun run apps:gen` twice produces zero diff.
 */

const HEADER = `// AUTO-GENERATED by \`bun run apps:gen\` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: apps/web/src/lib/tile-registry.ts (+ features/*/manifest.ts in
// Slice 5). Re-run \`bun run apps:gen\` after changing a tile; commit the result.`;

function renderTile(t: CollectedApp["tile"]): string {
  return `{ label: ${JSON.stringify(t.label)}, worldCol: ${t.worldCol}, worldRow: ${t.worldRow}, cols: ${t.cols}, rows: ${t.rows} }`;
}

function renderApp(a: CollectedApp): string {
  return [
    "  {",
    `    id: ${JSON.stringify(a.id)},`,
    `    tile: ${renderTile(a.tile)},`,
    `    guestExposed: ${a.guestExposed},`,
    `    home: ${a.home},`,
    `    sensitive: ${a.sensitive},`,
    `    source: ${JSON.stringify(a.source)},`,
    "  },",
  ].join("\n");
}

/** @public consumed by the `apps:gen` entrypoint (scripts/apps-gen.ts). */
export function renderTiles(model: AppModel): string {
  const sorted = [...model.apps].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const body = sorted.map(renderApp).join("\n");
  return `${HEADER}

export interface GeneratedTile {
  label: string;
  worldCol: number;
  worldRow: number;
  cols: number;
  rows: number;
}
export interface GeneratedApp {
  id: string;
  tile: GeneratedTile;
  guestExposed: boolean;
  home: boolean;
  sensitive: boolean;
  source: "feature" | "registry";
}

export const GENERATED_TILES: readonly GeneratedApp[] = [
${body}
];
`;
}

// ─── facet aggregates (Slice 5) ──────────────────────────────────────────────
// The following renderers emit the runtime-consumed barrels: the app router, the
// guest router, the drizzle schema barrel, and the (scaffolding) cron listing.
// Each is a deterministic projection of the collected features (sorted by dir),
// so `bun run apps:gen` twice is byte-identical.

const GEN_HEADER = `// AUTO-GENERATED by \`bun run apps:gen\` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,schema,jobs}.ts + apps/api/src/db/schema.ts.
// Re-run \`bun run apps:gen\` after changing a feature facet; commit the result.`;

/** features/<dir>/… -> a valid JS identifier base, e.g. "guest-wifi" -> "guestWifi". */
function ident(dir: string): string {
  return dir.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function sortedFeatures(model: AppModel): CollectedFeature[] {
  return [...model.features].sort((a, b) => (a.dir < b.dir ? -1 : a.dir > b.dir ? 1 : 0));
}

/** Render a `mergeRouters(...)` barrel over the given features' `api` facets. */
function renderRouterModule(features: CollectedFeature[], exportName: string): string {
  const withApi = features.filter((f) => f.hasApi);
  if (withApi.length === 0) {
    return `${GEN_HEADER}

import { router } from "@app-kit/server";

export const ${exportName} = router({});
`;
  }
  const imports = withApi
    .map((f) => `import { api as ${ident(f.dir)}Api } from "../${f.dir}/api";`)
    .join("\n");
  const args = withApi.map((f) => `${ident(f.dir)}Api`).join(", ");
  return `${GEN_HEADER}

import { mergeRouters } from "@app-kit/server";
${imports}

export const ${exportName} = mergeRouters(${args});
`;
}

/**
 * The generated app router: every feature `api` facet merged. apps/api's
 * routers/index.ts merges this with the non-feature base router.
 */
export function renderRouter(model: AppModel): string {
  return renderRouterModule(sortedFeatures(model), "featureAppRouter");
}

/**
 * The generated guest router (ADR-0006 security boundary): only features that
 * are BOTH `guestExposed` in their manifest AND present in the hand-owned
 * GUEST_EXPOSED allowlist. The guest listener mounts exactly this.
 */
export function renderGuestRouter(model: AppModel, guestExposed: readonly string[]): string {
  const allow = new Set(guestExposed);
  const guest = sortedFeatures(model).filter((f) => f.guestExposed && allow.has(f.id));
  return renderRouterModule(guest, "featureGuestRouter");
}

/**
 * The drizzle schema barrel drizzle-kit reads (drizzle.config.ts points here).
 * A union of the base apps/api schema with every feature schema, via relative
 * `export *` (drizzle-kit does not resolve tsconfig path aliases). The table set
 * is identical to the pre-fold schema, so `db:generate` sees no DROP.
 */
export function renderSchema(model: AppModel): string {
  const featureExports = sortedFeatures(model)
    .filter((f) => f.hasSchema)
    .map((f) => `export * from "../${f.dir}/schema";`)
    .join("\n");
  return `${GEN_HEADER}

export * from "../../apps/api/src/db/schema";
${featureExports}
`;
}

/**
 * The collected `defineCron` facets as a data listing (Track C forward
 * scaffolding — no runtime consumer yet; the real schedule stays in
 * infra/src/crons.ts). Sorted by (name, source) for determinism.
 */
export function renderCrons(model: AppModel): string {
  const sorted = [...model.crons].sort((a, b) =>
    a.name !== b.name
      ? a.name < b.name
        ? -1
        : 1
      : a.source < b.source
        ? -1
        : a.source > b.source
          ? 1
          : 0,
  );
  const body = sorted
    .map(
      (c) =>
        `  { name: ${JSON.stringify(c.name)}, schedule: ${JSON.stringify(c.schedule)}, source: ${JSON.stringify(c.source)} },`,
    )
    .join("\n");
  return `${GEN_HEADER}

export interface GeneratedCron {
  name: string;
  schedule: string;
  source: string;
}

export const GENERATED_CRONS: readonly GeneratedCron[] = [
${body}
];
`;
}
