import type { AppModel, CollectedFeature } from "./collect";

/**
 * Deterministic emitters for the collected {@link AppModel}. `tiles.gen.ts` is
 * the reviewable data projection; `web.gen.ts` is the static runtime aggregate
 * consumed by the Board and Tile Detail Host. Both come from the same validated
 * App manifests and Tile View facets.
 *
 * Determinism is the whole point: apps are sorted by `id` before rendering and
 * every field is emitted in a fixed key order, so `renderTiles(model)` is stable
 * across runs and `bun run apps:gen` twice produces zero diff.
 */

const HEADER = `// AUTO-GENERATED by \`bun run apps:gen\` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/manifest.ts.
// Re-run \`bun run apps:gen\` after changing a Tile; commit the result.`;

interface RenderableTile {
  id: string;
  appId: string;
  label: string;
  worldCol: number;
  worldRow: number;
  cols: number;
  rows: number;
  home: boolean;
  sensitive: boolean;
  private: boolean;
  source: "feature" | "registry";
}

function renderTile(t: RenderableTile): string {
  return [
    "  {",
    `    id: ${JSON.stringify(t.id)},`,
    `    appId: ${JSON.stringify(t.appId)},`,
    `    label: ${JSON.stringify(t.label)},`,
    `    worldCol: ${t.worldCol},`,
    `    worldRow: ${t.worldRow},`,
    `    cols: ${t.cols},`,
    `    rows: ${t.rows},`,
    `    home: ${t.home},`,
    `    sensitive: ${t.sensitive},`,
    `    private: ${t.private},`,
    `    source: ${JSON.stringify(t.source)},`,
    "  },",
  ].join("\n");
}

/** @public consumed by the `apps:gen` entrypoint (scripts/apps-gen.ts). */
export function renderTiles(model: AppModel): string {
  const tiles: RenderableTile[] = model.apps.flatMap((a) =>
    a.tiles.map((t) => ({
      id: t.id,
      appId: a.id,
      label: t.label,
      worldCol: t.worldCol,
      worldRow: t.worldRow,
      cols: t.cols,
      rows: t.rows,
      home: t.home,
      sensitive: a.sensitive,
      private: a.private,
      source: a.source,
    })),
  );
  const sorted = [...tiles].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const body = sorted.map(renderTile).join("\n");
  return `${HEADER}

export interface GeneratedTile {
  id: string;
  appId: string;
  label: string;
  worldCol: number;
  worldRow: number;
  cols: number;
  rows: number;
  home: boolean;
  sensitive: boolean;
  private: boolean;
  source: "feature" | "registry";
}

export const GENERATED_TILES: readonly GeneratedTile[] = [
${body}
];
`;
}

// ─── facet aggregates (Slice 5) ──────────────────────────────────────────────
// The following renderers emit the runtime-consumed barrels: the app router, the
// guest router, the drizzle schema barrel, and the (scaffolding) cron listing.
// Each is a deterministic projection of the collected features (sorted by dir),
// so `bun run apps:gen` twice is byte-identical.

const GEN_HEADER = `// AUTO-GENERATED by \`bun run apps:gen\` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,api,http,schema}.ts + apps/api/src/db/schema.ts.
// Re-run \`bun run apps:gen\` after changing a feature facet; commit the result.`;

const WEB_HEADER = `// AUTO-GENERATED by \`bun run apps:gen\` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/{manifest,detail}.ts.
// Re-run \`bun run apps:gen\` after changing an App web facet; commit the result.`;

const WORKER_HEADER = `// AUTO-GENERATED by \`bun run apps:gen\` (scripts/apps-gen.ts). DO NOT EDIT.
// Source of truth: features/*/worker.ts.
// Re-run \`bun run apps:gen\` after changing an App worker facet; commit the result.`;

/** features/<dir>/… -> a valid JS identifier base, e.g. "guest-wifi" -> "guestWifi". */
function ident(dir: string): string {
  return dir.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function sortedFeatures(model: AppModel): CollectedFeature[] {
  return [...model.features].sort((a, b) => (a.dir < b.dir ? -1 : a.dir > b.dir ? 1 : 0));
}

/** Static App web aggregate consumed by the Board and Tile Detail Host. */
export function renderWeb(model: AppModel): string {
  const features = sortedFeatures(model);
  const manifestImports = features
    .map((feature) => `import ${ident(feature.dir)}Manifest from "../${feature.dir}/manifest";`)
    .join("\n");
  const withDetail = features.filter((feature) => feature.hasDetail);
  const detailImports = withDetail
    .map(
      (feature) =>
        `import { tileViews as ${ident(feature.dir)}TileViews } from "../${feature.dir}/detail";`,
    )
    .join("\n");
  const manifests = features.map((feature) => `${ident(feature.dir)}Manifest`).join(",\n  ");
  const tileViews = withDetail.map((feature) => `...${ident(feature.dir)}TileViews`).join(",\n  ");

  return `${WEB_HEADER}

import { createWebRegistry } from "@app-kit";
${manifestImports}
${detailImports}

const manifests = [
  ${manifests},
];

const tileViews = [
  ${tileViews},
];

export const {
  TILE_REGISTRY,
  HOME_TILE,
  registryEntryForComponent,
  registryEntryForTileId,
  accessFor,
  getTileDetailEntry,
} = createWebRegistry(manifests, tileViews);

export type { TileAccessPolicy, TileRegistryEntry } from "@app-kit";
`;
}

/** Render a `mergeRouters(...)` barrel over the given features' `api` facets. */
function renderRouterModule(features: CollectedFeature[], exportName: string): string {
  const withApi = features.filter((f) => f.hasApi);
  if (withApi.length === 0) {
    return `${GEN_HEADER}

import { router } from "@app-kit/server";

export const ${exportName} = router({});
`;
  }
  const imports = withApi
    .map((f) => `import { api as ${ident(f.dir)}Api } from "../${f.dir}/api";`)
    .join("\n");
  const args = withApi.map((f) => `${ident(f.dir)}Api`).join(", ");
  return `${GEN_HEADER}

import { mergeRouters } from "@app-kit/server";
${imports}

export const ${exportName} = mergeRouters(${args});
`;
}

/**
 * The generated app router: every feature `api` facet merged. apps/api's
 * routers/index.ts merges this with the non-feature base router.
 */
export function renderRouter(model: AppModel): string {
  return renderRouterModule(sortedFeatures(model), "featureAppRouter");
}

/**
 * The drizzle schema barrel drizzle-kit reads (drizzle.config.ts points here).
 * A union of the base apps/api schema with every feature schema, via relative
 * `export *` (drizzle-kit does not resolve tsconfig path aliases). The table set
 * is identical to the pre-fold schema, so `db:generate` sees no DROP.
 */
export function renderSchema(model: AppModel): string {
  const featureExports = sortedFeatures(model)
    .filter((f) => f.hasSchema)
    .map((f) => `export * from "../${f.dir}/schema";`)
    .join("\n");
  return `${GEN_HEADER}

export * from "../../apps/api/src/db/schema";
${featureExports}
`;
}

/** Static aggregate of App-owned interval workers consumed by apps/worker. */
export function renderWorkers(model: AppModel): string {
  const withWorkers = sortedFeatures(model).filter((feature) => feature.hasWorker);
  if (withWorkers.length === 0) {
    return `${WORKER_HEADER}

import type { Worker } from "@app-kit";

export const GENERATED_WORKERS: readonly Worker[] = [];
`;
  }
  const imports = withWorkers
    .map(
      (feature) =>
        `import { cycles as ${ident(feature.dir)}Cycles } from "../${feature.dir}/worker";`,
    )
    .join("\n");
  const spread = withWorkers.map((feature) => `...${ident(feature.dir)}Cycles`).join(",\n  ");
  return `${WORKER_HEADER}

import type { Worker } from "@app-kit";
${imports}

export const GENERATED_WORKERS: readonly Worker[] = [
  ${spread},
];
`;
}

/**
 * The generated HTTP-route barrel (S3). Like `renderRouter` (a real import
 * barrel, not a data-only listing), this emits REAL imports of each collected
 * `defineHttp` module's `routes` export, spread into one `GENERATED_ROUTES`
 * array. `apps/api/src/server.ts`'s `findRoute` iterates it before the residual
 * hand-wired ladder. `model.httpModules` is already sorted deterministically in
 * `collect()`.
 */
export function renderHttp(model: AppModel): string {
  const mods = model.httpModules;
  if (mods.length === 0) {
    return `${GEN_HEADER}

import type { HttpRoute } from "@app-kit";

export const GENERATED_ROUTES: readonly HttpRoute[] = [];
`;
  }
  const imports = mods
    .map((m) => `import { routes as ${m.ident} } from "${m.importPath}";`)
    .join("\n");
  const spread = mods.map((m) => `...${m.ident}`).join(",\n  ");
  return `${GEN_HEADER}

import type { HttpRoute } from "@app-kit";
${imports}

export const GENERATED_ROUTES: readonly HttpRoute[] = [
  ${spread},
];
`;
}
