#!/usr/bin/env bash
set -euo pipefail

# Installs a persistent host NFS mount of the Synology "Homelab drive" on the
# Mac Mini (homelab), so the media-worker container can reach it via a plain
# bind-mount (containers on OrbStack have NO route to the LAN , the host must
# do the NFS; this is the same shape as the existing `maps` bind mount). www-kp4k.7
#
# Run ON homelab, as calum (NOT with sudo , it reads 1Password as you, then
# elevates only the install steps; you'll be prompted for your sudo password):
#
#   ./scripts/mount-homelab-drive.sh
#
# Idempotent. Installs a LaunchDaemon that mounts at boot and self-heals every 60s.

MOUNTPOINT="/Users/calum/control-center/media"
PLIST="/Library/LaunchDaemons/co.worldwidewebb.homelab-drive.plist"
WRAPPER="/usr/local/bin/homelab-drive-mount.sh"
LABEL="co.worldwidewebb.homelab-drive"

[ "$(id -u)" -ne 0 ] || { echo "FATAL: run as calum, NOT sudo (it needs op as you)" >&2; exit 1; }

# --- read NAS details from 1Password (kept out of the public repo) ----------
HOST=$(op read "op://Homelab/Homelab Drive/host")
SHARE=$(op read "op://Homelab/Homelab Drive/share")
PROTOCOL=$(op read "op://Homelab/Homelab Drive/protocol")
[ -n "$HOST" ] && [ -n "$SHARE" ] || { echo "FATAL: missing host/share in 1Password (run save-homelab-drive.sh first)" >&2; exit 1; }
[ "$PROTOCOL" = "nfs" ] || { echo "FATAL: this installer is NFS-only (protocol=$PROTOCOL)" >&2; exit 1; }
echo "NAS: $HOST:$SHARE  ->  $MOUNTPOINT"

echo "Elevating for install steps (enter your sudo password if prompted)..."
sudo mkdir -p "$MOUNTPOINT"

# --- self-healing mount wrapper (concrete values live on the private host) ---
sudo tee "$WRAPPER" >/dev/null <<WRAP
#!/bin/bash
# Auto-generated by scripts/mount-homelab-drive.sh , mounts the Homelab drive if not already.
MP="$MOUNTPOINT"
/sbin/mount | /usr/bin/grep -q " on \$MP " && exit 0
/sbin/mount_nfs -o vers=3,nolock,resvport,rw "$HOST:$SHARE" "\$MP"
WRAP
sudo chmod 755 "$WRAPPER"

# --- LaunchDaemon: run at boot + re-check every 60s -------------------------
sudo tee "$PLIST" >/dev/null <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key><array><string>$WRAPPER</string></array>
  <key>RunAtLoad</key><true/>
  <key>StartInterval</key><integer>60</integer>
  <key>StandardErrorPath</key><string>/var/log/homelab-drive-mount.log</string>
</dict>
</plist>
PLIST
sudo chmod 644 "$PLIST"

# --- (re)load -----------------------------------------------------------------
sudo launchctl bootout system "$PLIST" 2>/dev/null || true
sudo launchctl bootstrap system "$PLIST"
sudo launchctl kickstart -k "system/$LABEL" 2>/dev/null || true

# --- verify -------------------------------------------------------------------
sleep 2
echo "Verifying mount..."
if mount | grep -q " on $MOUNTPOINT "; then
  echo "  MOUNTED: $(mount | grep " on $MOUNTPOINT ")"
  TS="hello-world from homelab host nfs @ $(date -u)"
  if echo "$TS" > "$MOUNTPOINT/hello-world.txt" 2>/dev/null; then
    echo "  WROTE $MOUNTPOINT/hello-world.txt"
    ls -la "$MOUNTPOINT/hello-world.txt"
  else
    echo "  WRITE FAILED , if permission denied, set the NAS NFS Squash to 'Map all users to admin' and re-run."
  fi
else
  echo "  NOT MOUNTED , check /var/log/homelab-drive-mount.log"
  exit 1
fi
echo "DONE. Persistent across reboots; self-heals every 60s."
