// Decorative placeholder tiles — empty tile backgrounds that bento-tile the ENTIRE
// pannable world around the real cluster, so panning the canvas in any direction
// reveals a fully populated dashboard (flush tiles, varied sizes, no dotted voids,
// no empty frontier) rather than empty grid. They carry no content, are
// non-interactive, and never appear in the real registry.
//
// The fill is two layers:
//   1. INNER_FILL_LOCAL — the varied bento that tiles the inner 31×31 around the
//      real cluster (Clock at center). Coords are 0-indexed within that inner
//      region; they're shifted out by WALL_THICKNESS to land in world space.
//      Generated by a guillotine split, committed as data.
//   2. the WALL ring — a WALL_THICKNESS-cell-thick border of (mostly) 2×2 tiles
//      around the entire world edge, generated by buildWall(). It reads like a
//      wall enclosing the dashboard; same styling as the bento (no new tile type).
// After the shift the real cluster occupies world cols 15..26, rows 16..24. Every
// cell of the 35×35 world is covered exactly once (minus the cluster), asserted
// gap-free / overlap-free / sliver-free by placeholder-tiles.test.ts.
import {
  CLUSTER_COL_OFFSET,
  CLUSTER_ROW_OFFSET,
  WORLD_COLS,
  WORLD_ROWS,
  worldCellRect,
} from "./grid-constants";
import { TILE_REGISTRY } from "./tile-registry";

export type PlaceholderTile = {
  id: string;
  col: number;
  row: number;
  cols: number;
  rows: number;
};

// The inner bento fill: every non-cluster cell of the inner 31×31 region, tiled
// flush with varied sizes. Coords are 0-indexed within that inner region; shifted
// out by WALL_THICKNESS below to land in world space. Generated by a guillotine
// split, committed as data.
const INNER_FILL_LOCAL: PlaceholderTile[] = [
  { id: "tile_ph_001", col: 0, row: 0, cols: 5, rows: 3 },
  { id: "tile_ph_002", col: 5, row: 0, cols: 4, rows: 3 },
  { id: "tile_ph_003", col: 9, row: 0, cols: 2, rows: 2 },
  { id: "tile_ph_004", col: 11, row: 0, cols: 3, rows: 2 },
  { id: "tile_ph_005", col: 14, row: 0, cols: 4, rows: 2 },
  { id: "tile_ph_006", col: 18, row: 0, cols: 5, rows: 2 },
  { id: "tile_ph_007", col: 23, row: 0, cols: 5, rows: 2 },
  { id: "tile_ph_008", col: 28, row: 0, cols: 3, rows: 4 },
  { id: "tile_ph_009", col: 9, row: 2, cols: 2, rows: 3 },
  { id: "tile_ph_010", col: 11, row: 2, cols: 3, rows: 4 },
  { id: "tile_ph_011", col: 14, row: 2, cols: 4, rows: 2 },
  { id: "tile_ph_012", col: 18, row: 2, cols: 5, rows: 2 },
  { id: "tile_ph_013", col: 23, row: 2, cols: 5, rows: 4 },
  { id: "tile_ph_014", col: 0, row: 3, cols: 5, rows: 2 },
  { id: "tile_ph_015", col: 5, row: 3, cols: 4, rows: 3 },
  { id: "tile_ph_016", col: 14, row: 4, cols: 4, rows: 3 },
  { id: "tile_ph_017", col: 18, row: 4, cols: 5, rows: 2 },
  { id: "tile_ph_018", col: 28, row: 4, cols: 3, rows: 2 },
  { id: "tile_ph_019", col: 0, row: 5, cols: 5, rows: 3 },
  { id: "tile_ph_020", col: 9, row: 5, cols: 2, rows: 4 },
  { id: "tile_ph_021", col: 5, row: 6, cols: 4, rows: 2 },
  { id: "tile_ph_022", col: 11, row: 6, cols: 3, rows: 4 },
  { id: "tile_ph_023", col: 18, row: 6, cols: 5, rows: 4 },
  { id: "tile_ph_024", col: 23, row: 6, cols: 5, rows: 3 },
  { id: "tile_ph_025", col: 28, row: 6, cols: 3, rows: 3 },
  { id: "tile_ph_026", col: 14, row: 7, cols: 4, rows: 2 },
  { id: "tile_ph_027", col: 0, row: 8, cols: 5, rows: 4 },
  { id: "tile_ph_028", col: 5, row: 8, cols: 4, rows: 4 },
  { id: "tile_ph_029", col: 9, row: 9, cols: 2, rows: 2 },
  { id: "tile_ph_030", col: 14, row: 9, cols: 4, rows: 2 },
  { id: "tile_ph_031", col: 23, row: 9, cols: 5, rows: 3 },
  { id: "tile_ph_032", col: 28, row: 9, cols: 3, rows: 3 },
  { id: "tile_ph_033", col: 11, row: 10, cols: 3, rows: 4 },
  { id: "tile_ph_034", col: 18, row: 10, cols: 5, rows: 4 },
  { id: "tile_ph_035", col: 9, row: 11, cols: 2, rows: 3 },
  { id: "tile_ph_036", col: 14, row: 11, cols: 4, rows: 3 },
  { id: "tile_ph_037", col: 0, row: 12, cols: 5, rows: 2 },
  { id: "tile_ph_038", col: 5, row: 12, cols: 4, rows: 2 },
  { id: "tile_ph_039", col: 23, row: 12, cols: 5, rows: 2 },
  { id: "tile_ph_040", col: 28, row: 12, cols: 3, rows: 2 },
  { id: "tile_ph_041", col: 0, row: 14, cols: 5, rows: 3 },
  { id: "tile_ph_042", col: 5, row: 14, cols: 2, rows: 3 },
  { id: "tile_ph_043", col: 7, row: 14, cols: 3, rows: 4 },
  { id: "tile_ph_044", col: 10, row: 14, cols: 3, rows: 4 },
  { id: "tile_ph_045", col: 25, row: 14, cols: 2, rows: 4 },
  { id: "tile_ph_046", col: 27, row: 14, cols: 4, rows: 4 },
  { id: "tile_ph_047", col: 0, row: 17, cols: 5, rows: 4 },
  { id: "tile_ph_048", col: 5, row: 17, cols: 2, rows: 4 },
  { id: "tile_ph_049", col: 7, row: 18, cols: 3, rows: 3 },
  { id: "tile_ph_050", col: 10, row: 18, cols: 3, rows: 2 },
  { id: "tile_ph_051", col: 25, row: 18, cols: 2, rows: 2 },
  { id: "tile_ph_052", col: 27, row: 18, cols: 4, rows: 2 },
  { id: "tile_ph_053", col: 10, row: 20, cols: 3, rows: 3 },
  { id: "tile_ph_054", col: 25, row: 20, cols: 2, rows: 3 },
  { id: "tile_ph_055", col: 27, row: 20, cols: 4, rows: 3 },
  { id: "tile_ph_056", col: 0, row: 21, cols: 5, rows: 2 },
  { id: "tile_ph_057", col: 5, row: 21, cols: 2, rows: 2 },
  { id: "tile_ph_058", col: 7, row: 21, cols: 3, rows: 2 },
  { id: "tile_ph_059", col: 0, row: 23, cols: 5, rows: 3 },
  { id: "tile_ph_060", col: 5, row: 23, cols: 2, rows: 2 },
  { id: "tile_ph_061", col: 7, row: 23, cols: 2, rows: 2 },
  { id: "tile_ph_062", col: 9, row: 23, cols: 2, rows: 2 },
  { id: "tile_ph_063", col: 11, row: 23, cols: 2, rows: 4 },
  { id: "tile_ph_064", col: 13, row: 23, cols: 4, rows: 2 },
  { id: "tile_ph_065", col: 17, row: 23, cols: 5, rows: 2 },
  { id: "tile_ph_066", col: 22, row: 23, cols: 2, rows: 3 },
  { id: "tile_ph_067", col: 24, row: 23, cols: 3, rows: 3 },
  { id: "tile_ph_068", col: 27, row: 23, cols: 4, rows: 3 },
  { id: "tile_ph_069", col: 5, row: 25, cols: 2, rows: 4 },
  { id: "tile_ph_070", col: 7, row: 25, cols: 2, rows: 4 },
  { id: "tile_ph_071", col: 9, row: 25, cols: 2, rows: 3 },
  { id: "tile_ph_072", col: 13, row: 25, cols: 4, rows: 2 },
  { id: "tile_ph_073", col: 17, row: 25, cols: 5, rows: 2 },
  { id: "tile_ph_074", col: 0, row: 26, cols: 5, rows: 2 },
  { id: "tile_ph_075", col: 22, row: 26, cols: 2, rows: 3 },
  { id: "tile_ph_076", col: 24, row: 26, cols: 3, rows: 3 },
  { id: "tile_ph_077", col: 27, row: 26, cols: 4, rows: 3 },
  { id: "tile_ph_078", col: 11, row: 27, cols: 2, rows: 4 },
  { id: "tile_ph_079", col: 13, row: 27, cols: 4, rows: 4 },
  { id: "tile_ph_080", col: 17, row: 27, cols: 5, rows: 4 },
  { id: "tile_ph_081", col: 0, row: 28, cols: 5, rows: 3 },
  { id: "tile_ph_082", col: 9, row: 28, cols: 2, rows: 3 },
  { id: "tile_ph_083", col: 5, row: 29, cols: 2, rows: 2 },
  { id: "tile_ph_084", col: 7, row: 29, cols: 2, rows: 2 },
  { id: "tile_ph_085", col: 22, row: 29, cols: 2, rows: 2 },
  { id: "tile_ph_086", col: 24, row: 29, cols: 3, rows: 2 },
  { id: "tile_ph_087", col: 27, row: 29, cols: 4, rows: 2 },
];

// Thickness (in cells) of the decorative wall ring on every edge — one 2×2 tile.
// The world is 2*WALL_THICKNESS cells larger than the 31×31 inner region, so the
// inner fill (and the auto-recentred cluster) shift out by exactly this much.
export const WALL_THICKNESS = 2;

// The inner fill in world coords: shift each local tile out past the wall ring.
const INNER_FILL: PlaceholderTile[] = INNER_FILL_LOCAL.map((t) => ({
  ...t,
  col: t.col + WALL_THICKNESS,
  row: t.row + WALL_THICKNESS,
}));

// Build the wall ring: a WALL_THICKNESS-thick border of 2×2 tiles around the whole
// world. Each of the four bands is laid as a run of 2×2 tiles; because the world
// edge is odd (35) and the side bands are odd (31), one tile per band absorbs the
// leftover cell by being 3 long instead of 2 (still ≥2 on every side — no sliver).
// Together with INNER_FILL this covers every world cell exactly once.
function buildWall(): PlaceholderTile[] {
  const w = WALL_THICKNESS;
  const lastLo = w; // first inner column/row
  const lastHi = WORLD_COLS - w; // first column/row of the far wall band
  const tiles: PlaceholderTile[] = [];
  let n = 0;
  const id = () => `tile_wall_${String(++n).padStart(3, "0")}`;

  // A run of 2×2 tiles spanning `length` cells along one axis, with the final tile
  // widened to 3 when `length` is odd. `axis` picks which dimension the run walks.
  const run = (start: number, length: number, fixed: number, axis: "h" | "v"): void => {
    let pos = start;
    const end = start + length;
    while (pos < end) {
      const remaining = end - pos;
      const span = remaining === 3 ? 3 : 2; // odd tail (3) → one 3-long tile
      tiles.push(
        axis === "h"
          ? { id: id(), col: pos, row: fixed, cols: span, rows: w }
          : { id: id(), col: fixed, row: pos, cols: w, rows: span },
      );
      pos += span;
    }
  };

  // Top & bottom bands span the full width; left & right bands fill only the gap
  // between them, so corners belong to top/bottom and nothing overlaps.
  run(0, WORLD_COLS, 0, "h"); // top
  run(0, WORLD_COLS, lastHi, "h"); // bottom
  run(lastLo, lastHi - lastLo, 0, "v"); // left
  run(lastLo, lastHi - lastLo, lastHi, "v"); // right
  return tiles;
}

// Full decorative fill: inner bento (shifted into world space) + the wall ring.
export const BENTO_TILES: PlaceholderTile[] = [...INNER_FILL, ...buildWall()];

// World-pixel rects for every placeholder, for rendering + windowing in Board.
// Flush cells still get the standard gutter, because worldCellRect spaces tiles
// by CELL_PITCH (cell + gap) — identical spacing to the real cluster.
export const BENTO_RECTS: { id: string; rect: ReturnType<typeof worldCellRect> }[] =
  BENTO_TILES.map((p) => ({ id: p.id, rect: worldCellRect(p.col, p.row, p.cols, p.rows) }));

// ── validation (used by the test, kept beside the data it validates) ──

type Cell = { col: number; row: number; cols: number; rows: number };

function overlaps(a: Cell, b: Cell): boolean {
  return (
    a.col < b.col + b.cols &&
    a.col + a.cols > b.col &&
    a.row < b.row + b.rows &&
    a.row + a.rows > b.row
  );
}

// World-cell footprints of the real cluster, derived from the registry via the
// same offset the board uses — so the validator tracks the cluster automatically.
export function clusterWorldCells(): Cell[] {
  return TILE_REGISTRY.map((t) => ({
    col: t.colStart - 1 + CLUSTER_COL_OFFSET,
    row: t.rowStart - 1 + CLUSTER_ROW_OFFSET,
    cols: t.cols,
    rows: t.rows,
  }));
}

// The region the bento must fill: the entire world.
export function bentoRegion(): { c0: number; c1: number; r0: number; r1: number } {
  return { c0: 0, c1: WORLD_COLS - 1, r0: 0, r1: WORLD_ROWS - 1 };
}

function inCluster(col: number, row: number, cluster: Cell[]): boolean {
  return cluster.some(
    (c) => col >= c.col && col < c.col + c.cols && row >= c.row && row < c.row + c.rows,
  );
}

// Every layout invariant in one place: in-bounds, no self-overlap, no cluster
// overlap, no slivers (<2 cells per side), and FULL coverage of the world (every
// non-cluster cell covered exactly once). Empty == valid.
export function placeholderViolations(): string[] {
  const errs: string[] = [];
  const cluster = clusterWorldCells();
  const region = bentoRegion();

  for (const p of BENTO_TILES) {
    if (p.cols < 2 || p.rows < 2) errs.push(`${p.id} is a sliver (${p.cols}x${p.rows})`);
    if (
      p.col < region.c0 ||
      p.row < region.r0 ||
      p.col + p.cols - 1 > region.c1 ||
      p.row + p.rows - 1 > region.r1
    ) {
      errs.push(`${p.id} outside world`);
    }
    for (const c of cluster) {
      if (overlaps(p, c)) errs.push(`${p.id} overlaps real cluster`);
    }
  }
  for (let i = 0; i < BENTO_TILES.length; i++) {
    for (let j = i + 1; j < BENTO_TILES.length; j++) {
      if (overlaps(BENTO_TILES[i], BENTO_TILES[j])) {
        errs.push(`${BENTO_TILES[i].id} overlaps ${BENTO_TILES[j].id}`);
      }
    }
  }
  const covered = new Set<string>();
  for (const p of BENTO_TILES) {
    for (let r = p.row; r < p.row + p.rows; r++) {
      for (let c = p.col; c < p.col + p.cols; c++) covered.add(`${c},${r}`);
    }
  }
  for (let r = region.r0; r <= region.r1; r++) {
    for (let c = region.c0; c <= region.c1; c++) {
      if (inCluster(c, r, cluster)) continue;
      if (!covered.has(`${c},${r}`)) errs.push(`gap at cell ${c},${r}`);
    }
  }
  return errs;
}
