config:
  world-wide-webb-cloudflare:apiToken:
    secure: AAABAAC/5azu5Wj/L95XYLw/F6iRBLcobLvAoxI0/e+Aly+uEUp34WNIhVnQtaxi4qSE0CJf+slla+WiDxJaTxerTMRTfyE7LWxBCuPpQTR7cdu95g==
  world-wide-webb-cloudflare:allowedEmail:
    secure: AAABANmUI/prGE5l97uXkgfKXO7yR4CVNU3aURCVGgW6vkkrGx7LTyRsoyXS+XqIwDcMipjnV8eM
  world-wide-webb-cloudflare:accountId:
    secure: AAABAJ9EQ/c0AL9YYSZ08bufMr7uvPPyIkcSmUIeGT4RIQvydYlAgvBJgEoIRDf7c5pVfTRcAjjhIluW7ehSwQ==
  world-wide-webb-cloudflare:zoneId:
    secure: AAABAK+o1BMSlx2Xz7V+BxpIXUY4qxw+Pc4ek7WwlcDmnHVdMorgO5S3o1h5A/qrQNj1Cqyu6Kb8eL5XjFcndA==
  world-wide-webb-cloudflare:tunnelId:
    secure: AAABANey+hk/ECyTuWEAgrLRwf5XV5DXEJ08MPWQFvqV0Y0IBgvD39ANEPESpVpHAA4G9lUye4dtNs8nmY7QXbIfDW8=
  world-wide-webb-cloudflare:zoneName: worldwidewebb.co
  world-wide-webb-cloudflare:ciClientId:
    secure: AAABACsqHbau/ipUH6pTLW/ZK+6N/07Pr3o2LVUC0vaMVLBzMMuRmYI6s1IpBOBw5u6hMdWBD7bhmWj/JMD3xvBR/CzRgSw=
  world-wide-webb-cloudflare:kioskTokenId:
    secure: AAABAAxCBdFuE/9OBh3z51qiHAY1807osaDMQE7mKcnZv4F0g+4vwfoJzfc+LTTbkVzggyyvpGtISbaCLGWFdgSxPnw=
