import type { ScheduleSpec } from "@www/temporal-runtime";

export const WORKFLOW_TYPES = [
  "DtyeHealthCheckWorkflow",
  "OutboxDispatchRecoveryWorkflow",
  "SessionMaintenanceWorkflow",
  "NotificationDeliveryWorkflow",
  "ReportAccountabilityWorkflow",
  "UrgeRescueWorkflow",
  "StreakMilestoneSweepWorkflow",
  "InviteLifecycleWorkflow",
  "AccountDeletionWorkflow",
  "AccountDeletionHistorySweepWorkflow",
] as const;
export const MANAGED_SCHEDULE_PREFIX = "dtye_";
export const ACTIVITY_TYPES = [
  "DtyeHealthCheckActivity",
  "OutboxDispatchActivity",
  "SessionMaintenanceActivity",
  "prepareNotification",
  "deliverNotification",
  "suppressNotification",
  "rotatePushTokenBatch",
  "ReportAccountabilityActivity",
  "loadRescue",
  "advanceRescueAtDeadline",
  "eraseRescueForAccountDeletion",
  "StreakMilestoneSweepActivity",
  "loadInviteLifecycle",
  "requestInviteReminder",
  "eraseAccountLocally",
  "revokeAppleCredential",
  "finishAccountDeletion",
  "terminateAssociatedWorkflows",
  "deleteAssociatedWorkflowHistories",
  "sweepAccountDeletionHistories",
  "purgeExpiredAccountDeletionRecords",
  "recordAccountDeletionErasureStuck",
] as const;
export const SCHEDULES = [
  {
    scheduleId: "dtye_health",
    workflowType: "DtyeHealthCheckWorkflow",
    cron: "* * * * *",
    timezone: "UTC",
    args: { schemaVersion: 1 },
    timeout: "2 minutes",
    catchupWindow: "1 minute",
  },
  {
    scheduleId: "dtye_outbox_recovery",
    workflowType: "OutboxDispatchRecoveryWorkflow",
    cron: "* * * * *",
    timezone: "UTC",
    args: { schemaVersion: 1 },
    timeout: "5 minutes",
    catchupWindow: "1 minute",
  },
  {
    scheduleId: "dtye_streak_sweep",
    workflowType: "StreakMilestoneSweepWorkflow",
    cron: "0 * * * *",
    timezone: "UTC",
    args: { schemaVersion: 1 },
    timeout: "10 minutes",
    catchupWindow: "1 minute",
  },
  {
    scheduleId: "dtye_account_deletion_history_sweep",
    workflowType: "AccountDeletionHistorySweepWorkflow",
    cron: "23 * * * *",
    timezone: "UTC",
    args: { schemaVersion: 1 },
    timeout: "10 minutes",
    catchupWindow: "1 hour",
  },
  {
    scheduleId: "dtye_session_maintenance",
    workflowType: "SessionMaintenanceWorkflow",
    cron: "17 3 * * *",
    timezone: "UTC",
    args: { schemaVersion: 1 },
    timeout: "10 minutes",
    catchupWindow: "1 minute",
  },
] as const satisfies readonly ScheduleSpec[];
